### ISSUE TITLE
Pressing backspace during boot makes system panick

### ISSUE THREAD

**Issue by Pollux3737** [Sup3Legacy/FerrOS#20]
![image](https://user-images.githubusercontent.com/29065455/107974674-3becb900-6fb7-11eb-823f-e6660f63180f.png)

**Comment by Sup3Legacy** [comment]
In fact any key pressed during the early stages of OS startup and initialization can cause this panic, because it can happen before the `scancodeQueue` has been initialized. 

I think locking the keyboard interrupt handling system could resolve this issue. Or maybe disable all interrupts until full OS startup

**Comment by Sup3Legacy** [comment]
This should have been resolved in #22 !
